name: Deploy Quarto Site
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: quarto-dev/quarto-actions/render@v2
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
